import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";

export const openSans = Open_Sans({
  weight: ["300", "400", "500", "600", "700", "800"],
  subsets: ["latin"],
  display: "swap",
  fallback: ["Arial", "sans-serif"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` text-sm sm:text-[15px] ${openSans.className} antialiased`}
      >
      {children}
      </body>
    </html>
  );
}
